### ISSUE TITLE
Implementing a C-compatible `tzset` in terms of tz-rs

### ISSUE THREAD

**Issue by sunfishcode** [x-hgg-x/tz-rs#35]
I am looking to implement a C-compatible `tzset` function in terms of tz-rs, and am curious if you know of a way to wire this up. It seems `tzset` needs to determine the following information:

 - `daylight`: does the local timezone ever have daylight savings time rules applied?
 - `timezone`: UTC offset of local *standard* time
 - `tzname[0]`: the name of the local *standard* designation
 - `tzname[1]`: the name of the local *daylight savings* designation

I can get the local time time from tz-rs like this:

```rust
    let time_zone_local = TimeZone::local()?;
    let local_time_type = time_zone_local.find_current_local_time_type();
```

That leaves me with a few questions:
 - Is `local_time_type.is_dst()` the same as `daylight`, or is it an indication of whether dst is presently active?
 - Is `local_time_type.time_zone_desgination()` the currently active designation, or is it always for the standard designation?
 - Is `local_time_type.ut_offset()` for the currently active designation, or is it always for the standard designation?
 - Is there a way to retrieve both the standard and dst designations?

Any help you might be able to provide would be greatly appreciated!

**Comment by x-hgg-x** [comment]
Glibc documentation: https://www.gnu.org/software/libc/manual/html_node/Time-Zone-Functions.html.

The `daylight` field is `0` if we are in local standard time, and typically `1` if we are in DST, and another value if there are DST rules but we can't say if they apply or not. If we know the time in UTC, we always know if the DST is set, for example with `time_zone_local.find_current_local_time_type()` in `tz-rs`.

But if we only know the local datetime but not the UTC offset, for example by calling [`mktime`](https://en.cppreference.com/w/c/chrono/mktime) with `tm_isdst = -1` (corresponding to `DateTime::find()` in `tz-rs`), we can have an ambiguous time with several matching possibilities. Depending on the implementation, the `daylight` field may be set to another value. In `tz-rs`, the DST value for a `LocalTimeType` is fixed, and the `DateTime::find()` method can return several `DateTime`, each containing a single `LocalTimeType`. 

The `timezone`, `tzname[0]` and `tzname[1]` fields can be retrieved from the `extra_rule` field of the `TimeZone`. It is an optional field since the information may not be available from the timezone, but all current timezones used with the `tzdb` crate contains the field. Additionnaly, since we store the UTC offset in each `LocalTimeType`, we must reverse its sign to obtain the `timezone` value.

In your example, `local_time_type` contains only the `LocalTimeType` for the current time, by calling `SystemTime::now()` internally to obtain the time in UTC and then finding the infos in the provided timezone.

**Comment by sunfishcode** [comment]
Thanks! This got me on track, and I was able to implement a `tzset` and several other functions which appear to be working in simple tests at least. In case anyone's curious, the code is in https://github.com/sunfishcode/mustang/pull/182.
